pipeline {
    agent {
        docker {
            image 'node:gallium-bullseye'
            args '-p 3000:3000'
        }
    }
    options {
            ansiColor('xterm')
    }
    environment {
        CI = 'False'
        HOME = '.'
        NODE_ENV='development'
        npm_config_cache = 'npm-cache'
        aws_credential = "s3-uploader"
        bucket = "bamzy-info-builds"
        region = "ca-central-1"
      }
    stages {
        stage('Build chartAPI') {
            steps {
                echo '\033[32m'
                sh 'cd apis/chart && npm install'
                sh 'cp apis/chart/.env-copy apis/chart/.env'
                sh 'echo \'PORT=8081 \n \'  >> apis/chart/.env'
                sh 'echo \'SQS_URL=https://sqs.ca-central-1.amazonaws.com/593885178555/bamzy-sqs \n \'  >> apis/chart/.env'
            }
        }
        stage('Run jest tests for chartAPI') {
            steps {
                echo '\033[34m'
                sh 'cd apis/chart && npx jest'
            }
        }

    }
}